# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Biomedical Informatics Entrepreneurs Salon
email: bies-info@hms.harvard.edu
admin_email: bies-admin@hms.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  To promote entrepreneurship at the convergence of biology, medicine, and computing.
  We hold monthly meetups at Harvard Medical School, Boston, MA
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bioinformaticssalon" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  bioinformaticssalon

# Build settings
markdown: kramdown
